# Generated by Django 3.2.25 on 2024-10-29 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuFuuApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='', upload_to='productos/'),
            preserve_default=False,
        ),
    ]
