# Generated by Django 3.2.25 on 2024-10-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuFuuApp', '0002_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estrellas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
