# Generated by Django 5.1.15 on 2025-12-18 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuFuuApp', '0006_orden_itemorden_pago_orden_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemorden',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orden',
            options={'ordering': ['-fecha']},
        ),
        migrations.RemoveField(
            model_name='orden',
            name='codigo_postal',
        ),
        migrations.AddField(
            model_name='itemorden',
            name='notas_admin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='aprobada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orden',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('pendiente_revision', 'Pendiente de Revisión'), ('aprobada', 'Aprobada'), ('pagado', 'Pagado'), ('procesando', 'Procesando'), ('enviado', 'Enviado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente_revision', max_length=25),
        ),
        migrations.AlterField(
            model_name='orden',
            name='pago',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BuFuuApp.pago'),
        ),
    ]
